# Generated by Django 5.1.5 on 2025-03-19 13:16

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(null=True, upload_to=base.models.upload_vid_path),
        ),
    ]
